version: 2.1

jobs:
  build:
  
    working_directory: ~/circleci-hockeyhero 

    docker: 
      - image: circleci/openjdk:8-jdk-stretch #primary container
      - image: circleci/mysql:latest # secondary container

    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_DATABASE: hockeyhero_nearest
        SPRING_PROFILES_ACTIVE: test
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: ''
        SPRING_JPA_HIBERNATE_DDL-AUTO: none   
        SPRING_DATASOURCE_URL: jdbc:mysql://root@localhost/hockeyhero_nearest?useUnicode=true&characterEncoding=utf8

    steps: 
   
      - checkout 

      - restore_cache: 
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: circleci-hockeyhero-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline 
      
      # saves the project dependencies
      - save_cache: 
          paths:
            - ~/.m2
          key: circleci-hockeyhero-{{ checksum "pom.xml" }}
      
      # build the jar
      - run: mvn package 

      # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.       
      - store_test_results: 
          # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: target/surefire-reports
      
      # store the uberjar as an artifact
      - store_artifacts: 
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: target/hockeyhero_nearest-0.0.1-SNAPSHOT.jar
         # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples 

